Initial commit
SviatRudik/Task3.0 pull request #12
Opened 2022-01-11 09:56 UTC by SviatRudik

2022-01-12 07:24 UTC, VladimirBaklan requested changes

2022-01-12 07:24 UTC, VladimirBaklan commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.5.5","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["A:\\JDK/bin/java","-Xms100m","-Xmx100m","-classpath","C:/Users/свят/AppData/Roaming/JetBrains/IntelliJIdea2021.3
Must be in gitingore

2022-01-12 07:24 UTC, VladimirBaklan commented on build.sbt
> +  "com.typesafe.akka" %% "akka-http-spray-json" % "10.2.7",
Why the versions are not the same? 
Also, in sbt file you are able to create variables, so akka versions sounds like a candidate for it

2022-01-12 07:24 UTC, VladimirBaklan commented on build.sbt
> +  "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % "2.13.1",
Why do you need that?

2022-01-12 07:24 UTC, VladimirBaklan commented on build.sbt
> +flywayLocations += "db/migration"
Sounds like configuration

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/resources/application.conf
> +  }}
Formatting?

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/resources/db/migration/V1__Create_tables.sql
> +    foreign key (user_id) references users (user_id),
It's ok, but just FYI, you can add foreign keys using the following way:
```
user_id INT NOT NULL REFERENCES users(user_id)
```

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/com/scala/entity/rideModels.scala
> +case class Ride(duration: Int, startDate: LocalDateTime, endDate: LocalDateTime, startStationNumber: String,
Formatting

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/Routes.scala
> +  private val user = new UsersApi
https://habr.com/ru/post/350068/

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/api/BikesApi.scala
> +  private val service = new BikeServiceImpl
https://habr.com/ru/post/350068/

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/util/Materializer.scala
> +trait Materializer {
Why do you need to store it in trait?

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/util/DatabaseConfig.scala
> +class DatabaseConfig extends Config {
Why not singleton?

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/util/Config.scala
> +trait Config {
Why trait?

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/service/UserServiceImpl.scala
> +    UsersDao.createUser(user)
https://habr.com/ru/post/350068/

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/queries/BikesQueries.scala
> +    for{b<-bikesTable.drop(offset).take(limit)}yield b.bikeName
Why not map?

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/models/package.scala
> +  type StationId = Long
👍

2022-01-12 07:24 UTC, VladimirBaklan commented on src/main/scala/web/mappings/JsonMappings.scala
> +trait JsonMappings extends DefaultJsonProtocol {
Why trait?

2022-01-14 07:42 UTC, VladimirBaklan requested changes

2022-01-14 07:42 UTC, VladimirBaklan commented on src/main/resources/application.conf
> +}
Formatting

2022-01-14 07:42 UTC, VladimirBaklan commented on src/main/scala/web/apis/FileApi.scala
> +          complete(s"Successfully completed fileUpload")
It doesn't look similar to the REST api.

2022-01-16 17:30 UTC, VladimirBaklan commented on src/main/scala/com/scala/utils/ConverterUtil.scala
> +  def convertToRides(seqOfLines: Seq[String]): Seq[Ride] = {
Public methods should always be on top

2022-01-16 17:41 UTC, VladimirBaklan requested changes

2022-01-16 17:41 UTC, VladimirBaklan commented on src/main/scala/web/Routes.scala
> +  private val user           = new UsersApi(userService)
Are you sure that this is the right place to create objects? 
What if there will be background job that uses some services?

2022-01-16 17:41 UTC, VladimirBaklan commented on src/main/scala/web/utils/AppConfig.scala
> +  ): AppConfig = {
It seems like the object doesn't make sense here. 
Why not to make configuration globally accessible?

2022-01-16 17:41 UTC, VladimirBaklan commented on src/main/scala/web/utils/DatabaseConfig.scala
> +  implicit val session: Session = db.createSession()
One session per project sounds extreme. 
Also, I don't think you should use a session. Usually it's enough to use Database and let slick handle sessions

2022-01-16 17:41 UTC, VladimirBaklan commented on src/main/scala/web/utils/FlywayConfig.scala
> +}
First of all, why class and not case class? 
And why did you decide to move the constructor outside of the class?

2022-01-16 17:41 UTC, VladimirBaklan commented on src/main/scala/web/daos/StationsDaoComponent.scala
> +trait StationsDaoComponent {
What does `Component` mean?

2022-01-16 17:41 UTC, VladimirBaklan commented on src/main/scala/web/mappings/JsonMappings.scala
> +class JsonMappings extends DefaultJsonProtocol {
Why is it a class and not an object?

2022-01-16 17:41 UTC, VladimirBaklan commented on src/main/scala/web/daos/StatsDao.scala
> +      } yield trip
This is not right, try to read slick documentation related to the transactional calls again

2022-01-16 17:41 UTC, VladimirBaklan commented on src/main/scala/web/apis/BikesApi.scala
> +        parameters('limit.as[Int], 'offset.as[Int]) { (limit, offset) =>
![image](https://user-images.githubusercontent.com/34661735/149671368-8be28415-5ef9-402e-8a9f-0e03f69560e2.png)

2022-01-18 12:15 UTC, DaniilShkurski requested changes

2022-01-18 12:15 UTC, DaniilShkurski commented on src/main/scala/com/scala/utils/ConverterUtil.scala
> +  private def convertToRide(line: String, correctIndexOfElement: Seq[Int]): Option[Ride] = {
I think that part of this functionality should go under an apply(str: String) constuctor in companion object

2022-01-18 12:15 UTC, DaniilShkurski commented on src/main/scala/com/scala/utils/ResultFileCreator.scala
>  class ResultFileCreator {
I think instead of creating config instances there, we need to add either a Config field to class, or just use instead of the whole AppConfig here only configuration parts we need and create case classes for them as well (databaseConfig, fileNameConfig, ect.)

2022-01-18 13:16 UTC, DaniilShkurski requested changes

2022-01-18 13:16 UTC, DaniilShkurski commented on src/main/scala/web/mappings/JsonMappings.scala
> +  implicit val userFormat    = jsonFormat2(User)
I'm ok with it, but ideally i would create an objet for each of those case classes and provide implicits there.
Not sure if it's allowed for this task, but i think to avoid issues with defining json encoders and decoders here you should use Circe. https://circe.github.io/circe/
@VladimirBaklan is it allowed to be used in this task?

2022-01-18 13:16 UTC, DaniilShkurski commented on src/main/scala/web/models/package.scala
> +package object models {
Is it necessary to define those types? I think it could bring more confusion

2022-01-18 13:16 UTC, DaniilShkurski commented on src/main/scala/web/utils/AppConfig.scala
> +class AppConfig {
Not sure if it's allowed by the requirements, but ideally i would use PureConfig here
https://pureconfig.github.io/
@VladimirBaklan is it allowed to use it?

If not, at least i would create separate classes for database and fileconfig and defining them as fields

2022-01-18 13:16 UTC, DaniilShkurski commented on src/main/scala/web/utils/Flyway.scala
> +  def flywayMigrate: MigrateResult = {
i would define a config field  in that method, so it'll be easier to test

2022-01-18 13:48 UTC, SviatRudik commented on src/main/scala/web/models/package.scala
> +package object models {
https://github.com/SviatRudik/Task3.0/pull/12#discussion_r782770352

2022-01-18 14:18 UTC, VladimirBaklan commented on src/main/scala/web/utils/AppConfig.scala
> +class AppConfig {
I wouldn't introduce PureConfig for now

2022-01-18 14:19 UTC, VladimirBaklan commented on src/main/scala/web/mappings/JsonMappings.scala
> +  implicit val userFormat    = jsonFormat2(User)
You could use kebs-spray to make json format definition easier, but let's not use circe

2022-01-19 14:15 UTC, DaniilShkurski commented on src/main/scala/com/scala/utils/ConverterUtil.scala
> +  private def convertToRide(line: String, correctIndexOfElement: Seq[Int]): Option[Ride] = {
After discussion decided to leave it as it is, as this is a specific string parsing case which is used only here

2022-01-19 15:21 UTC, VladimirBaklan commented on build.sbt
> +  "com.typesafe.slick" %% "slick" % "3.4.0-M1",
Slick version could be constant, because slick-hikaricp uses the same version as well

2022-01-19 15:27 UTC, VladimirBaklan commented on src/main/scala/web/Routes.scala
> +) {
You can avoid using `val` in the constructor, just `bikeService: BikeService`. 
You have to use `val` only if it's an override

2022-01-19 15:38 UTC, VladimirBaklan commented on src/main/scala/web/models/package.scala
> +package object models {
It would be nice to have typed Ids, like: `case class BikeId(value: Long)` for type-safety. 
Typed aliases won't help you with passing invalid arguments, but at least it improves readability. 
In huge projects it's an overhead, but for some simple apps like that - it's ok

2022-01-19 15:40 UTC, VladimirBaklan commented on src/main/scala/web/services/TripServiceImpl.scala
> +  override def updateTrip(newTrip: Trip, tripId: TripId): Future[Int] = {
What is the trip with provided id does not exist?

2022-01-19 15:41 UTC, VladimirBaklan commented on src/main/scala/web/utils/configClasses.scala
> +  val httpPort      = httpConfig.getInt("port")
You can make all these fields private

2022-01-24 11:36 UTC, VladimirBaklan approved these changes

2022-01-24 11:40 UTC, DaniilShkurski approved these changes

2022-01-24 12:31 UTC, merged